version: '3.8'

services:
  app:
    image: mona333/traffic-sign:latest
    # build: .
    ports:
      - "8080:8080" 
    volumes:
      - .:/app:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "main.py"]
    devices:
      - "/dev/video0:/dev/video0"
